# -*- coding: utf-8 -*-

{
  "name"                 :  "giga SaaS Kit",
  "summary"              :  """giga SaaS Kit allows you to run your giga As A SaaS business. After installation and set uo you can sell giga As A Saas to your client via subscription based model""",
  "category"             :  "Extra Tools",
  "version"              :  "1.1.4",
  "sequence"             :  1,
  'author': 'HGHS Haus Garten, Handels- Service - Gesellschaft mbH',
  'website': 'https://www.badmoebel-guenstig.net/pages/gratis',
  "license"              :  "Other proprietary",
  "description"          :  """Provide giga as a Service(Saas) on your servers with giga saas Kit.""",
  "live_test_url"        :  "",
  "depends"              :  [
                             'sale_management',
                             'portal',
                             'base',
                             'website_sale',
                             'account',
                            ],
  "data"                 :  [
                             'security/giga_saas_kit_security.xml',
                             'security/ir.model.access.csv',
                             'views/res_config_views.xml',
                             #'views/templates.xml',
                             'data/contract_sequence.xml',
                             'data/client_sequence.xml',
                             'data/email_templates.xml',
                             'views/subdomain_page.xml',
                             'data/recurring_invoice_cron.xml',
                             'data/client_creation_cron.xml',
                             'views/saas_server_view.xml',
                             'views/module_category_view.xml',
                             'wizards/contract_creation_view.xml',
                             'views/saas_plan_view.xml',
                             'views/module_view.xml',
                             'views/product_view.xml',
                             'views/account_invoice_view.xml',
                             'views/saas_contract_view.xml',
                             'views/saas_client_view.xml',
                             'views/sale_view.xml',
                             'views/saas_portal_templates.xml',
                             'views/menuitems.xml',
                            ],
  "assets"               : {
       'web.assets_backend': [
           'giga_saas_kit/static/src/js/subdomain_page.js',
       ],
  },
  "application"          :  True,
  "installable"          :  True,
  "auto_install"         :  False,
  "price"                :  999,
  "currency"             :  "EUR",
  "pre_init_hook"        :  "pre_init_check",
  "external_dependencies":  {'python': ['urllib']},
}
